#Libs
All: libutil libgraphics libdata libllist libCEthread

libutil: 
		(cd util && make)

libgraphics: 
		(cd graphics && make)

libdata:
		(cd data && make)

libllist:
		(cd linkedlist && make)

libCEthread:
		(cd CEthread && make)